/// Modding framework recognizes certain files that will be automatically digested by the engine.
/// This is the list of directory prefixes that are used to check if given file is one of those features.
pub const knownFeatures: []const []const []const u8 = &.{
	&.{"callbacks", "block", "client"},
	&.{"callbacks", "block", "server"},
	&.{"callbacks", "block", "touch"},
	&.{"commands"},
	&.{"ecs", "client", "components"},
	&.{"ecs", "server", "components"},
	&.{"ecs", "storage"},
	&.{"ecs", "systems"},
	&.{"gui", "components"},
	&.{"gui", "windows"},
	&.{"items"},
	&.{"key_binds"},
	&.{"modifiers"},
	&.{"network", "protocols"},
	&.{"procedural_item", "modifiers", "restrictions"},
	&.{"procedural_item", "modifiers"},
	&.{"rotations"},
	&.{"sync", "atomics"},
	&.{"sync", "messages"},
	&.{"sync", "transactions"},
	&.{"terrain", "cave_biome_gen"},
	&.{"terrain", "cave_gen"},
	&.{"terrain", "chunk_gen"},
	&.{"terrain", "climate_gen"},
	&.{"terrain", "map_gen"},
	&.{"terrain", "sdf_models"},
	&.{"terrain", "simple_structures"},
	&.{"terrain", "structure_map_gen"},
};

pub const Feature = enum(usize) {
	other,
	@"callbacks/block/client",
	@"callbacks/block/server",
	@"callbacks/block/touch",
	commands,
	@"ecs/client/components",
	@"ecs/server/components",
	@"ecs/storage",
	@"ecs/systems",
	@"gui/components",
	@"gui/windows",
	items,
	key_binds,
	modifiers,
	@"network/protocols",
	@"procedural_item/modifiers/restrictions",
	@"procedural_item/modifiers",
	rotations,
	@"sync/atomics",
	@"sync/messages",
	@"sync/transactions",
	@"terrain/cave_biome_gen",
	@"terrain/cave_gen",
	@"terrain/chunk_gen",
	@"terrain/climate_gen",
	@"terrain/map_gen",
	@"terrain/sdf_models",
	@"terrain/simple_structures",
	@"terrain/structure_map_gen",
};
